### ISSUE TITLE
2.0.9

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/phalcon-ppa#16]
[Phalcon 2.0.9 released](https://github.com/phalcon/cphalcon/releases/tag/phalcon-v2.0.9)

**Comment by skaasjager** [comment]
@sergeyklay, I believe @thecodeassassin is currently on holiday, but I'll create the pull requests for v2.0.9 today.

I did already upload v2.0.9 packages to the PPA on Launchpad and they are now available to install.

**Comment by sergeyklay** [comment]
@andresgutierrez

**Comment by skaasjager** [comment]
Created pull requests #17  #18 #19 and #20 for updating to v2.0.9

**Comment by skaasjager** [comment]
@sergeyklay, thanks for merging! The issue can be closed.
