### ISSUE TITLE
v2.0.10 is available

### ISSUE THREAD

**Issue by skaasjager** [phalcon/phalcon-ppa#21]
Just noticed that v2.0.10 is available. I will build the new package today or tomorrow.

**Comment by sergeyklay** [comment]
:+1:

**Comment by skaasjager** [comment]
Pull requests created and ready to be merged. Packages have been built and are being released as I type.

**Comment by skaasjager** [comment]
PR's are: #22 #23 #24 #25

**Comment by skaasjager** [comment]
Hmmm keep the PR's from merging, builds are failing?
`/«PKGBUILDDIR»/cphalcon/build/64bits/phalcon.zep.c: In function 'zephir_return_property_quick':
/«PKGBUILDDIR»/cphalcon/build/64bits/phalcon.zep.c:6039:80: error: 'zend_property_info' has no member named 'offset'
/«PKGBUILDDIR»/cphalcon/build/64bits/phalcon.zep.c:6041:26: error: 'zend_object' has no member named 'properties_table'
/«PKGBUILDDIR»/cphalcon/build/64bits/phalcon.zep.c:6041:58: error: 'zend_property_info' has no member named 'offset'
/«PKGBUILDDIR»/cphalcon/build/64bits/phalcon.zep.c:6044:18: error: 'zend_object' has no member named 'properties_table'
/«PKGBUILDDIR»/cphalcon/build/64bits/phalcon.zep.c:6044:50: error: 'zend_property_info' has no member named 'offset'`

**Comment by skaasjager** [comment]
UPDATE: only Precise failed to build. It is an LTS release, with support until April 2017.

**Comment by skaasjager** [comment]
@andresgutierrez, did you see this error message? Seems you were tagged in a closed PR thread, which might have dropped off the radar?

**Comment by sergeyklay** [comment]
@skaasjager Ubuntu Precise use PHP 5.3 API

**Comment by skaasjager** [comment]
@sergeyklay ah, yes, that makes sense. :-)

For Xenial, we have to wait for 2.1 with php7 support, I guess.
