### ISSUE TITLE
Debian jessie packaging

### ISSUE THREAD

**Issue by HanXHX** [phalcon/phalcon-ppa#27]
Hi,

I work on debian jessie packaging: https://github.com/HanXHX/phalcon-debian (repository: http://apt.debianiste.org).

Do you want to work together?

Cheers.

Emilien

**Comment by sergeyklay** [comment]
Hello

Could you please collaborate with @dzubchik
As far as I know he's trying to create a project designed for the building Phalcon for different versions of PHP & Linux.

Anyway good news!

**Comment by sergeyklay** [comment]
@HanXHX This is still actual?

**Comment by HanXHX** [comment]
Yep I'm still working on it.

**Comment by sergeyklay** [comment]
Well, I'm interested to work together. You can contact with me via serghei@phalconphp.com

**Comment by sergeyklay** [comment]
https://github.com/phalcongelist/packagecloud
